//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("K4GDW Software")]
[assembly: AssemblyCopyright("Copyright © K4GDW 2013")]
[assembly: AssemblyTrademark("K4GDW")]
[assembly: AssemblyProduct("PoweruP")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0.0")]
[assembly: AssemblyTitle("PoweruP")]
[assembly: AssemblyDescription("A simple console app that generates the \'anytime\' scripts for an existing database.")]


